const productsObj = [
	{
		title: "Wildstone Infra Hotel",
		description: "2715 Ash Dr. San Jose, South Dakota",
		imgLink: "./dist/assets/images/photo1.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Viroth’s Hotel",
		description: "Siem Reap, Kambodża",
		imgLink: "./dist/assets/images/photo2.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Tulemar Bungalows & Villas",
		description: "Park Narodowy Manuel Antonio, Kostaryka",
		imgLink: "./dist/assets/images/photo3.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Umaid Bhawan Palace Jodhpu",
		description: "Jodhpur, Indie",
		imgLink: "./dist/assets/images/photo4.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Hanoi La Siesta Hotel & Spa",
		description: " Hanoi, Wietnam",
		imgLink: "./dist/assets/images/photo5.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo6.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo7.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo8.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo9.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	//
	{
		title: "Wildstone Infra Hotel",
		description: "2715 Ash Dr. San Jose, South Dakota",
		imgLink: "./dist/assets/images/photo1.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Viroth’s Hotel",
		description: "Siem Reap, Kambodża",
		imgLink: "./dist/assets/images/photo2.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Tulemar Bungalows & Villas",
		description: "Park Narodowy Manuel Antonio, Kostaryka",
		imgLink: "./dist/assets/images/photo3.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Umaid Bhawan Palace Jodhpu",
		description: "Jodhpur, Indie",
		imgLink: "./dist/assets/images/photo4.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Hanoi La Siesta Hotel & Spa",
		description: " Hanoi, Wietnam",
		imgLink: "./dist/assets/images/photo5.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo6.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo7.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo8.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo9.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Wildstone Infra Hotel",
		description: "2715 Ash Dr. San Jose, South Dakota",
		imgLink: "./dist/assets/images/photo1.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Viroth’s Hotel",
		description: "Siem Reap, Kambodża",
		imgLink: "./dist/assets/images/photo2.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Tulemar Bungalows & Villas",
		description: "Park Narodowy Manuel Antonio, Kostaryka",
		imgLink: "./dist/assets/images/photo3.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Umaid Bhawan Palace Jodhpu",
		description: "Jodhpur, Indie",
		imgLink: "./dist/assets/images/photo4.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Hanoi La Siesta Hotel & Spa",
		description: " Hanoi, Wietnam",
		imgLink: "./dist/assets/images/photo5.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo6.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo7.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo8.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo9.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	//
	{
		title: "Wildstone Infra Hotel",
		description: "2715 Ash Dr. San Jose, South Dakota",
		imgLink: "./dist/assets/images/photo1.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Viroth’s Hotel",
		description: "Siem Reap, Kambodża",
		imgLink: "./dist/assets/images/photo2.webp",
		alt: "dodaj alt pozniej",
		category: "komercyjne",
	},
	{
		title: "Tulemar Bungalows & Villas",
		description: "Park Narodowy Manuel Antonio, Kostaryka",
		imgLink: "./dist/assets/images/photo3.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Umaid Bhawan Palace Jodhpu",
		description: "Jodhpur, Indie",
		imgLink: "./dist/assets/images/photo4.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Hanoi La Siesta Hotel & Spa",
		description: " Hanoi, Wietnam",
		imgLink: "./dist/assets/images/photo5.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo6.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo7.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo8.webp",
		alt: "dodaj alt pozniej",
		category: "mieszkaniowe",
	},
	{
		title: "Gili Lankanfushi",
		description: "Lankanfushi, Malediwy",
		imgLink: "./dist/assets/images/photo9.webp",
		alt: "dodaj alt pozniej",
		category: "inne",
	},
];
